### ISSUE TITLE
Provide a function that calculates the difference in business days between two dates

### ISSUE THREAD

**Issue by datenzauberai** [MarcoGorelli/polars-business#10]
Would be cool to have a function that calculates the number of business days between two dates.

**Comment by MarcoGorelli** [comment]
totally, thanks for your request and for checking this out!

**Comment by MarcoGorelli** [comment]
🤔 what might be a good name for this function...maybe `count_days_until`? So you'd write
```python
df.with_columns(
    plb.col('start_date').bdt.count_days_until('end_dates')
```

**Comment by datenzauberai** [comment]
Uh, naming discussions are always so dangerous... I would go with something simple like diff (used by many date related frameworks) and not fix the time unit (days) and the direction (until) in the method name.

```
pl.col("date").dt.offset_by("1mo_saturating")).bdt.diff(pl.col("date")).alias("businessDaysTillMonthEnd")
```

**Comment by MarcoGorelli** [comment]
yeah diff would be good I just worry that it's easily confused with the already existing [Expr.diff](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.diff.html)

**Comment by datenzauberai** [comment]
You're totally right. The diff way to do it would even make perfect sense and could be helpful in the bdt namespace as well. It's just a different thing :-) Maybe `sub` would be better than? Because this would really be a special kind of subtraction (https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.sub.html) and you could still reserve diff for subtracting with the preceding element.

**Comment by MarcoGorelli** [comment]
ah, perfect! I wasn't actually aware of `Expr.sub` - cool, let's go with that then, thanks! going to try to get an initial solution out today

**Comment by datenzauberai** [comment]
Most civilized naming discussion ever 🤣

**Comment by MarcoGorelli** [comment]
I've ended up adding `plb.workday_count` too, that should be more familiar for anyone coming from numpy, e.g.
```python
In [9]: df.with_columns(
   ...:     result = plb.workday_count(
   ...:         'Day1',
   ...:         'Day2',
   ...:         weekend=['Thu', 'Fri', 'Sat', 'Sun'],
   ...:     )
   ...: )
Out[9]:
shape: (6, 5)
┌────────┬──────────┬────────────┬────────────┬────────┐
│ Market ┆ Service  ┆ Day1       ┆ Day2       ┆ result │
│ ---    ┆ ---      ┆ ---        ┆ ---        ┆ ---    │
│ str    ┆ str      ┆ date       ┆ date       ┆ i32    │
╞════════╪══════════╪════════════╪════════════╪════════╡
│ AT     ┆ Standard ┆ 2022-01-02 ┆ 2022-01-05 ┆ 2      │
│ DE     ┆ Express  ┆ 2022-01-03 ┆ 2022-01-09 ┆ 3      │
│ AT     ┆ Standard ┆ 2022-01-04 ┆ 2022-01-09 ┆ 2      │
│ CZ     ┆ Standard ┆ 2022-01-05 ┆ 2022-01-09 ┆ 1      │
│ GB     ┆ Standard ┆ 2022-01-06 ┆ 2022-01-09 ┆ 0      │
│ CZ     ┆ Standard ┆ 2022-01-07 ┆ 2022-01-15 ┆ 3      │
└────────┴──────────┴────────────┴────────────┴────────┘
```
