### ISSUE TITLE
Maybe rename the namespace to `bdt` ?

### ISSUE THREAD

**Issue by ion-elgreco** [MarcoGorelli/polars-business#11]
Just a thought I had while using it, maybe it could make more sense to have naming closer to `.dt`. 

And while typing this out, I am also thinking how `.bdt` would work when you want to do rolling on business date ranges. Anyhow just a thought :)

**Comment by MarcoGorelli** [comment]
hmm yeah, maybe that would be better, thanks

and then have `.bdt.offset_by`, but it can only accept strings of the form `'<n>bd'`

will think about it - in the meantime, thanks for your request and for having tried this out!

**Comment by MarcoGorelli** [comment]
this is now available in version 0.1.26
