### ISSUE TITLE
Consolidate advance_n_days in `business.offset_by`

### ISSUE THREAD

**Issue by ion-elgreco** [MarcoGorelli/polars-business#12]
The offset_by API is quite useful and lends itself probably also easy to extend to support `bh`, `bd` etc. Would also make the API more familiar.

**Comment by MarcoGorelli** [comment]
Thanks for the suggestion!

Right, so the rule could be:
- if you pass `'<n>bd'`, that will be processed in accordance with the business day rules you've defined in `weekend` and `holidays`
- anything else will be passed down to `.dt.offset_by`

So, for example, `.bdt.offset_by('3bd1h')` means "move forwards by 3 business days, and then by 1 hour".

Once we introduce business hours, we can also parse `bh`
