### ISSUE TITLE
Custom namespace not recognized by linter

### ISSUE THREAD

**Issue by ion-elgreco** [MarcoGorelli/polars-business#13]
So I am not sure if this issue should be created here or in polars or py03-polars. But using a polars plugin or creating a custom expr namespace both have these issue where the linter doesn't recognize the namespace and says you're accessing a member that doesn't exist. I can silence the errors with noqa but this would be not ideal once more and more of these plugins will pop up 😄 

```
Cannot access member "business" for type "Expr"
  Member "business" is unknownPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(function) business: Unknown
```

**Comment by MarcoGorelli** [comment]
true that - thanks for the report, and for trying this out!

cc @alexander-beedie in case you have suggestions

**Comment by alexander-beedie** [comment]
I have yet to come up with a good generic approach to this (outside of per-project `.pyi` typing stubs), as _static_ type-checkers obviously know nothing about _dynamic_ property registration. Not sure if mypy/pylance offer any dedicated extension points for this sort of thing, but it's a real pain-point for all kinds of dynamic registration patterns 😅

**Comment by MarcoGorelli** [comment]
right - there might be a solution there

to define `polars_business.col`, which is the same as `polars.col`, but the return type is typed to know about `.bdt`

then, linting / auto-complete should work:

![image](https://github.com/MarcoGorelli/polars-business/assets/33491632/445512c2-4356-4d57-ba7b-7447d1d7d8bd)

**Comment by MarcoGorelli** [comment]
just made a new release, seems to work! 🎉 

![image](https://github.com/MarcoGorelli/polars-business/assets/33491632/e77685d9-ca61-4457-9a7b-5b0201666f92)

**Comment by ion-elgreco** [comment]
Nice workaround! Curious though what happens if you have multiple plugins later, would all of them expose their namespaces through their own `.col`

**Comment by MarcoGorelli** [comment]
yeah maybe

it's just a trick to get autocomplete, it's still pl.col underneath, the code is just
```python
class BColumn(Protocol):
    def __call__(
        self,
        name: str | PolarsDataType | Iterable[str] | Iterable[PolarsDataType],
        *more_names: str | PolarsDataType,
    ) -> BExpr:
        ...

    def __getattr__(self, name: str) -> pl.Expr:
        ...

    @property
    def bdt(self) -> ExprBusinessDateTimeNamespace:
        ...


col = cast(BColumn, pl.col)
```
