### ISSUE TITLE
update py3o-polars

### ISSUE THREAD

**Issue by ritchie46** [MarcoGorelli/polars-business#14]
If you point to the latest main, you will get a compiler error.

You can fix that by renaming `type_func` to `output_type_func`.

That would make this repo in line with the docs. :)

**Comment by MarcoGorelli** [comment]
thanks

> update py3o-polars

Am I not already poiting to the latest commit from pyo3-polars? https://github.com/pola-rs/pyo3-polars/commits/main

https://github.com/MarcoGorelli/polars-business/blob/ad4b67f44178910bd2108338739c45958e64d761/polars_business/polars_business/Cargo.toml#L14

**Comment by MarcoGorelli** [comment]
tried this, but
```
error: custom attribute panicked
  --> src/expressions.rs:17:1
   |
17 | #[polars_expr(output_type_func=bday_output)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: didn't recognize attribute
```
