### ISSUE TITLE
date_range with custom weekend / holidays

### ISSUE THREAD

**Issue by JustinKurland** [MarcoGorelli/polars-business#16]
@MarcoGorelli one nice thing to add here as you work on the business day logic would be the following:

Default business day logic: Monday, Tuesday, Wednesday, Thursday, Friday
Alternate business day logic: Sunday, Monday, Tuesday, Wednesday, Thursday

I have recently done this here on a package I have developing: [link](https://github.com/business-science/pytimetk/blob/master/src/pytimetk/core/make_timeseries_sequence.py)

I have some further `datetime` ideas that probably better off in `polars` as issues, but they are also largely around finding sensible alignment between `pandas` and `polars`.  For example, it is quite easy to "floor" a date in `polars` with `truncate()` but ceiling a date is much more difficult. Attached is some hackery to do what I mean currently, which is not great, so this seems worthwhile trying to solve for.

<img width="399" alt="Screen Shot 2023-10-20 at 1 18 50 PM" src="https://github.com/MarcoGorelli/polars-business/assets/65054169/2110f078-18ea-40ae-9ed3-cb03b5114772">
<img width="399" alt="Screen Shot 2023-10-20 at 1 18 59 PM" src="https://github.com/MarcoGorelli/polars-business/assets/65054169/8f2e32d5-3ccd-40cd-bfea-3c6a6bb216cd">

**Comment by MarcoGorelli** [comment]
hey @JustinKurland , thanks for the request

regarding the alternative workweek, you can already pass `weekend=['Fri', 'Sat']` - does that not give you what you're asking for?

**Comment by MarcoGorelli** [comment]
example:
```python
result = df.with_columns(
    date_shifted=pl.col("date").business.advance_n_days(
      n=5,
      weekend=['Sun'],
    )
)
print(result)

shape: (3, 2)
┌────────────┬──────────────┐
│ date       ┆ date_shifted │
│ ---        ┆ ---          │
│ date       ┆ date         │
╞════════════╪══════════════╡
│ 2023-04-03 ┆ 2023-04-08   │
│ 2023-09-01 ┆ 2023-09-07   │
│ 2024-01-04 ┆ 2024-01-10   │
└────────────┴──────────────┘
```

**Comment by JustinKurland** [comment]
Absolutely, that works, but in following on from the thread in `polars`, in the event of wanting to create a range of business days that also account for the holidays of the particular alternative work week. Apologies if I was not clear.

**Comment by MarcoGorelli** [comment]
yup, I plan to add something like `.bdt.date_range`. it should already be quite simple though:

```python
In [5]: import holidays
   ...:
   ...: start = date(2020, 1, 1)
   ...: end = date(2020, 2, 1)
   ...: uk_holidays = list(holidays.country_holidays("UK", years=[2020]))
   ...:
   ...: expr = pl.date_range(start, end)
   ...: expr = expr.filter(~expr.is_in(uk_holidays))
   ...: expr = expr.filter(expr.dt.weekday().is_in([1,2,3,4,7]))
   ...: pl.select(expr)
Out[5]:
shape: (21, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2020-01-02 │
│ 2020-01-05 │
│ 2020-01-06 │
│ 2020-01-07 │
│ …          │
│ 2020-01-27 │
│ 2020-01-28 │
│ 2020-01-29 │
│ 2020-01-30 │
└────────────┘
```

**Comment by MarcoGorelli** [comment]
>  For example, it is quite easy to "floor" a date in polars with truncate() but ceiling a date is much more difficult

could you open an issue in polars directly about this one please? IIUC it's not business-logic specific

**Comment by JustinKurland** [comment]
> >  For example, it is quite easy to "floor" a date in polars with truncate() but ceiling a date is much more difficult
> 
> 
> 
> could you open an issue in polars directly about this one please? IIUC it's not business-logic specific

Will do @MarcoGorelli 🙌🏻
