### ISSUE TITLE
Does `offset_by` with UK holidays count the right number of holidays?

### ISSUE THREAD

**Issue by ianozsvald** [MarcoGorelli/polars-business#20]
I think that the offset for business days with UK holidays is off by one - what did I miss?

2023-04-03 (Monday 3rd) shifted by 5 days, with UK Holidays, I think should skip Friday 7th and Monday 10th as they are UK Bank Holidays. I think 3rd April + 5 days via UK Holidays should yield Wednesday 12th, not Tuesday April 11th, no? Without UK Holidays (second example below) with the same offset the 3rd + 5 bd gives Monday 10th.

```
# taken from README
In [38]: from datetime import date
    ...: 
    ...: import polars as pl
    ...: import polars_business as plb
    ...: 
    ...: df = pl.DataFrame(
    ...:     {"date": [date(2023, 4, 3), date(2023, 9, 1), date(2024, 1, 4)]}
    ...: )

In [40]: result = df.with_columns(
    ...:     date_shifted=plb.col("date").bdt.offset_by('5bd', holidays=uk_holidays)
    ...: )
    ...: print(result)
shape: (3, 2)
┌────────────┬──────────────┐
│ date       ┆ date_shifted │
│ ---        ┆ ---          │
│ date       ┆ date         │
╞════════════╪══════════════╡
│ 2023-04-03 ┆ 2023-04-11   │ # LOOKS WRONG (only 1 of 2 holidays applied?)
│ 2023-09-01 ┆ 2023-09-08   │ # LOOKS OK
│ 2024-01-04 ┆ 2024-01-11   │ # LOOKS OK
└────────────┴──────────────┘
```

If I remove the `uk_holidays` offse we get 3rd->10th which makes sense (2 day weekend and we ignore the Friday and Monday Bank Holidays):

```
In [39]: result = df.with_columns(
    ...:     date_shifted=plb.col("date").bdt.offset_by('5bd')
    ...: )
    ...: print(result)
shape: (3, 2)
┌────────────┬──────────────┐
│ date       ┆ date_shifted │
│ ---        ┆ ---          │
│ date       ┆ date         │
╞════════════╪══════════════╡
│ 2023-04-03 ┆ 2023-04-10   │ # LOOKS OK (no holidays applied)
│ 2023-09-01 ┆ 2023-09-08   │ # LOOKS OK
│ 2024-01-04 ┆ 2024-01-11   │ # LOOKS OK
└────────────┴──────────────┘
```

Versions:

```
In [35]: pl.__version__
Out[35]: '0.19.11'

In [36]: plb.__version__
Out[36]: '0.1.29'
```

**Comment by MarcoGorelli** [comment]
first, thanks a tonne for trying this out! much appreciated

so, let's count

- 2023-04-03 this is a Monday.
- 2023-04-04 this is a Tuesday.
- 2023-04-05 this is a Wednesday.
- 2023-04-06 this is a Thursday.
- ~2023-04-07 this is a holiday.~
- ~2023-04-08 this is a Saturday~
- ~2023-04-08 this is a Sunday~
- 2023-04-09 this is a Monday.
- 2023-04-10 this is a Tuesday.

This looks correct?

**Comment by MarcoGorelli** [comment]
OK I see the issue:
```python
In [12]: import holidays

In [13]: holidays.country_holidays('UK', years=[2023])
Out[13]: {datetime.date(2023, 5, 8): 'Coronation of Charles III', datetime.date(2023, 1, 1): "New Year's Day", datetime.date(2023, 1, 2): "New Year's Day (Observed)", datetime.date(2023, 12, 25): 'Christmas Day', datetime.date(2023, 12, 26): 'Boxing Day', datetime.date(2023, 4, 7): 'Good Friday', datetime.date(2023, 5, 1): 'May Day', datetime.date(2023, 5, 29): 'Spring Bank Holiday'}
```

The `holidays` Python package doesn't know about Easter Monday (10th of April)

**Comment by MarcoGorelli** [comment]
Ah right, looks like it's correct https://github.com/vacanza/python-holidays/issues/1449

They don't count the 10th of April as it's not a holiday throughout all of the UK

If we want it to be counted, we need to do it like this:
```python
In [20]: result = df.with_columns(
    ...:      date_shifted=plb.col("date").bdt.offset_by('5bd', holidays=list(uk_holidays))
    ...: )

In [21]: result
Out[21]:
shape: (3, 2)
┌────────────┬──────────────┐
│ date       ┆ date_shifted │
│ ---        ┆ ---          │
│ date       ┆ date         │
╞════════════╪══════════════╡
│ 2023-04-03 ┆ 2023-04-12   │
│ 2023-09-01 ┆ 2023-09-08   │
│ 2024-01-04 ┆ 2024-01-11   │
└────────────┴──────────────┘
```
which I think is what you were probably expecting?

**Comment by MarcoGorelli** [comment]
I've added `subdiv='England'` to the README example so this is clearer to future readers - thanks for the issue!

**Comment by ianozsvald** [comment]
Thanks for fixing, I've added a mention in my newsletter: https://buttondown.email/NotANumber/archive/develop-faster-with-python-312-profile-multi-core/

**Comment by MarcoGorelli** [comment]
Very kind of you thanks Ian!
