### ISSUE TITLE
Error in _get_shared_lib_location(__file__) due to missing .so or .dll file

### ISSUE THREAD

**Issue by Viktor-Crettenand** [MarcoGorelli/polars-business#23]
When importing polars_business I get an error in:
lib = _get_shared_lib_location(__file__)

This function calls:
def _get_shared_lib_location(main_file: Any) -> str:
    import os
    directory = os.path.dirname(main_file)  # noqa: PTH120
    return os.path.join(  # noqa: PTH118
        directory, next(filter(is_shared_lib, os.listdir(directory)))
    )

Which filters the files in the __file__ directory using:
def is_shared_lib(file: str) -> bool:
    return file.endswith((".so", ".dll"))

Since there are no .so and .dll files in the __file__ folder the library doesn't import successfully. 

I installed polars-business using pip install polars-business.

**Comment by MarcoGorelli** [comment]
hey @Viktor-Crettenand 

which polars version are you using? which platform? can you show your error message please?

**Comment by Viktor-Crettenand** [comment]
Hi Marco,
I'm using Polars 0.19.12 from the pypi_0 build. What do you refer to by platform?

Here is the error message: 
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[46], line 3
      1 import pandas as pd
      2 import polars as pl
----> 3 import polars_business as plb
      4 pd.options.mode.chained_assignment = None
      5 import warnings

File [c:\Miniconda\envs\excel\Lib\site-packages\polars_business\__init__.py:13](file:///C:/Miniconda/envs/excel/Lib/site-packages/polars_business/__init__.py:13)
     10 from polars.type_aliases import PolarsDataType
     11 from typing import Sequence, cast, Iterable, Protocol
---> 13 lib = _get_shared_lib_location(__file__)
     15 __version__ = "0.3.4"
     17 mapping = {"Mon": 1, "Tue": 2, "Wed": 3, "Thu": 4, "Fri": 5, "Sat": 6, "Sun": 7}

File [c:\Miniconda\envs\excel\Lib\site-packages\polars\utils\udfs.py:881](file:///C:/Miniconda/envs/excel/Lib/site-packages/polars/utils/udfs.py:881), in _get_shared_lib_location(main_file)
    877 import os
    879 directory = os.path.dirname(main_file)  # noqa: PTH120
    880 return os.path.join(  # noqa: PTH118
--> 881     directory, next(filter(is_shared_lib, os.listdir(directory)))
    882 )

StopIteration:

**Comment by Viktor-Crettenand** [comment]
I think polars-business is looking for a .so or .dll file in folder: <python environment> \Lib\site-packages\polars_business
The files I have there after running the command: pip install polars-business are: __pycache__, __init__.py, polars_business.cp311-win_amd64.pyd, py.typed, ranges.py.
Can someone with a working setup check what files they have in this folder?

**Comment by MarcoGorelli** [comment]
thanks 

> What do you refer to by platform?

windows / linux / macos - looks like you're on windows, and using miniconda?

I've also tried, and get the same error!

```python
(base) C:\Users\User>python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
>>> import polars_business as plb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\mambaforge\lib\site-packages\polars_business\__init__.py", line 13, in <module>
    lib = _get_shared_lib_location(__file__)
  File "C:\Users\User\mambaforge\lib\site-packages\polars\utils\udfs.py", line 881, in _get_shared_lib_location
    directory, next(filter(is_shared_lib, os.listdir(directory)))
StopIteration
>>>
```

Same thing happens with the polars-hash plugin:
```python
>>> import polars_hash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\mambaforge\lib\site-packages\polars_hash\__init__.py", line 6, in <module>
    lib = _get_shared_lib_location(__file__)
  File "C:\Users\User\mambaforge\lib\site-packages\polars\utils\udfs.py", line 881, in _get_shared_lib_location
    directory, next(filter(is_shared_lib, os.listdir(directory)))
StopIteration
```

So, looks like something in the plugin systemm may need changing - @ritchie46 just FYI (I haven't yet looked into it further)

**Comment by Viktor-Crettenand** [comment]
Oh right of course. Yes Windows and Miniconda.
