### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by ashishbajpai** [MarcoGorelli/polars-business#24]
Thanks for creating this Marco. However running into issue getting started. I have installed the latest polars and polars-business versions -- 
polars                    0.19.12
polars-business           0.3.4
 
but getting the following error when running the snippet below.

>>> from datetime import date
>>> import polars as pl
>>> import polars_business as plb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\workspace\projects\Lib\site-packages\polars_business\__init__.py", line 13, in <module> 
    lib = _get_shared_lib_location(__file__)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\workspace\projects\Lib\site-packages\polars\utils\udfs.py", line 881, in _get_shared_lib_location
    directory, next(filter(is_shared_lib, os.listdir(directory)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

**Comment by MarcoGorelli** [comment]
Hey @ashishbajpai there's a bug in Polars but it's fixed now, when they release the next version then the plugin will work again on Windows

**Comment by ashishbajpai** [comment]
Thanks, will try again after the next polars release.

**Comment by MarcoGorelli** [comment]
this should be resolved by the latest polars release (0.19.13) - closing then, but thanks for the issue!

**Comment by ashishbajpai** [comment]
Thanks for the quick update Marco, just tried and it works great!
