### ISSUE TITLE
failed on python 3.9 because syntax introduced in 3.10 is used

### ISSUE THREAD

**Issue by uchiiii** [MarcoGorelli/polars-business#30]
### Current
I used this plugin on Python 3.9 env and got the error below.
```
Traceback (most recent call last):
  File "/home/uchiiii/polars_example/src/polars_example/20231201.py", line 4, in <module>
    import polars_business as plb
  File "/home/uchiiii/polars_example/.venv/lib/python3.9/site-packages/polars_business/__init__.py", line 8, in <module>
    from polars_business.ranges import date_range
  File "/home/uchiiii/polars_example/.venv/lib/python3.9/site-packages/polars_business/ranges.py", line 14, in <module>
    start: date | datetime | IntoExprColumn,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
This is because a syntax introduced in Python 3.10 is used.
https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator

I believe python 3.9 is supported by this plugin.
https://github.com/MarcoGorelli/polars-business/blob/22b90bb6e2c1f02cd939ef95a55f8928c47e86d1/polars_business/polars_business/pyproject.toml#L19

### Expect
Run without any error

### How to reproduce
- env
```
$ python --version
Python 3.9.16
$ cat pyproject.toml
...
dependencies = [
    "polars>=0.19.7",
    "matplotlib>=3.8.0",
    "polars-business>=0.3.15",
]
...
```
- code
```python
from datetime import date

import polars as pl
import polars_business as plb


df = pl.DataFrame(
    {"date": [date(2023, 4, 3), date(2023, 9, 1), date(2024, 1, 4)]}
)

result = df.with_columns(
    date_shifted=plb.col("date").bdt.offset_by(
        '5bd',
        weekend=('Sat', 'Sun'),
    )
)
print(result)
```

**Comment by uchiiii** [comment]
I am willing to make a PR to support 3.8 and 3.9. Is it ok?

**Comment by MarcoGorelli** [comment]
thanks @uchiiii ! that's embarassing

I think we just need `from __future__ import annotations` at the top of the file - fancy making a PR?

**Comment by MarcoGorelli** [comment]
this is quite embarassing actually - maybe I'll just put a quick fix in and release a new version?

**Comment by MarcoGorelli** [comment]
i've opened https://github.com/MarcoGorelli/polars-business/pull/31

**Comment by uchiiii** [comment]
Thanks for your quick fix!

**Comment by MarcoGorelli** [comment]
no, thank _you_! should be fixed in the latest release if you'd like to try it

**Comment by uchiiii** [comment]
I confirmed the code runs without any errors! thanks!
