### ISSUE TITLE
proposals to improve readabillity as an example (cookiecutter) expression plugin

### ISSUE THREAD

**Issue by ritchie46** [MarcoGorelli/polars-business#9]
Here are some proposals that will help users to grok this repo better.

1. remove example directory and flatten the structure 
2. remove the code from pyo3_polars and just point to the git repo in Cargo.toml (later to crates.io)
3. move business days logic to separate module, so that it is clear what the expression dispatchers are and where we interface with polars.

**Comment by MarcoGorelli** [comment]
thanks for your feedback, much appreciated!

I think I've addressed everything - any further comments would be very welcome

**Comment by ritchie46** [comment]
Looking good :+1:
